language: generic

matrix:
  include:
    - os: osx
      env:
        - ARCH=x86_64
        - MINIFORGE_NAME="Miniforge-pypy3"
        - OS_NAME="MacOSX"

    - os: osx
      env:
        - ARCH=x86_64
        - MINIFORGE_NAME="Miniforge3"
        - OS_NAME="MacOSX"

    - os: linux
      env:
        - ARCH=aarch64
        - DOCKER_ARCH=arm64v8
        - DOCKERIMAGE=condaforge/linux-anvil-aarch64
        - MINIFORGE_NAME="Miniforge3"
        - OS_NAME="Linux"

    - os: linux
      env:
        - ARCH=x86_64
        - DOCKER_ARCH=amd64
        - DOCKERIMAGE=condaforge/linux-anvil-comp7
        - MINIFORGE_NAME="Miniforge3"
        - OS_NAME="Linux"

    - os: linux
      env:
        - ARCH=ppc64le
        - DOCKER_ARCH=ppc64le
        - DOCKERIMAGE=condaforge/linux-anvil-ppc64le
        - MINIFORGE_NAME="Miniforge3"
        - OS_NAME="Linux"

    - os: linux
      env:
        - ARCH=aarch64
        - DOCKER_ARCH=arm64v8
        - DOCKERIMAGE=condaforge/linux-anvil-aarch64
        - MINIFORGE_NAME="Miniforge-pypy3"
        - OS_NAME="Linux"

    - os: linux
      env:
        - ARCH=x86_64
        - DOCKER_ARCH=amd64
        - DOCKERIMAGE=condaforge/linux-anvil-comp7
        - MINIFORGE_NAME="Miniforge-pypy3"
        - OS_NAME="Linux"

    - os: linux
      env:
        - ARCH=ppc64le
        - DOCKER_ARCH=ppc64le
        - DOCKERIMAGE=condaforge/linux-anvil-ppc64le
        - MINIFORGE_NAME="Miniforge-pypy3"
        - OS_NAME="Linux"

script:
  - if [[ "$TRAVIS_TAG" != "" ]]; then export MINIFORGE_VERSION=$TRAVIS_TAG; fi
  - if [[ "$OS_NAME" == "Linux" ]]; then bash build_miniforge.sh; fi
  - if [[ "$OS_NAME" == "MacOSX" ]]; then bash build_miniforge_osx.sh; fi
  # Copy for latest release
  - cp build/$MINIFORGE_NAME-*-$OS_NAME-$ARCH.sh build/$MINIFORGE_NAME-$OS_NAME-$ARCH.sh
  - ls -alh build

deploy:
  provider: releases
  # Token from conda-forge-bot (run by isuruf)
  api_key:
    secure: lB9JNCDM1KM+tEhVDqrOpJgTUnWeu1rTr1nedhaivauUaLh3A/jM7bs7V/4/Rjr1qlOq2OPuHOLS32J4Oz14j3f2s1LuLCO9TizEvA2RDQv/m6mfvCd/VfLF73y6oCY8qgPs6nk1c0cvTjCGe5o7rDAWDhezWOPME2+JxQUAzNH1dM52p+rzvNWFzZfYj0bmJNpuKfm0Q0nwOwUUkz23/m2BCra4dx+UU7Wc+JL2Zx77EMDQXHSUPQ+Bp1BMghUR8zC6Lizx2hCPFCtvehqPEdCAqO8wxWUZiUczylAhK2WK4DtvJBnVzvUEy+7ez1SMzaGBamrM21wW/Gwmt/8u0ZwcbnYuFaVRgZObvYwdFGAl0G75ZEF8WEzeLsik/Hf7Q0nygAC+60s0rbxHlX9WTRVthSS1wr6awOS0PsK0QLZPACEBTCT7epUBrNSNWwGxdymj2/6pKqyj1OM1NUbq9PlJMcWcIDuWLizYNCijyqvX5wqcGSSyKa5+ad365fQIl45mN9rBv9cxvEjrHB4X6h9pW4DyYesN5CF6i2446SAP4zG8YwDp7rG092yNYuxix0GTlyWyI4Pd+QryhYYCFZqnv2ZXipGNrDtS/N2QVJOaR1k/pAZ6Fd1m1bK6pfG5DSEoLFpu+ckITVfJslIR9BEdmZuyEuF26tHjagr2Itg=
  file:
    - "build/Miniforge*.sh"
    - "build/Miniforge*.sha256"
  file_glob: true
  on:
    repo: conda-forge/miniforge
    tags: true
  skip_cleanup: true
