name: Check for new conda releases
on:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  check_conda_release:
    name: "Check for release and open issue"
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run Actions script
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/conda_release.js`)
            console.log(script({github, context}))
