name: Lint
on: [ pull_request ]
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f # v3.2.0
      - name: Install dependencies
        run: |
          conda install -c conda-forge shellcheck
      - name: Shellcheck
        run: |
          echo "::add-matcher::.github/shellcheck-matcher.json"
          shellcheck --format=gcc $(find . -iname "*.sh")
          echo "::remove-matcher owner=shellcheck::"
