name: Lint
on: [ pull_request ]
jobs:
  lint:
    runs-on: ubuntu-slim
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3.3.0
      - name: Install dependencies
        run: |
          conda install -c conda-forge shellcheck
      - name: Shellcheck
        run: |
          echo "::add-matcher::.github/shellcheck-matcher.json"
          shellcheck --format=gcc $(find . -iname "*.sh")
          echo "::remove-matcher owner=shellcheck::"
